package main;

import lib.Parser;

class Main {
  public static void main(String args[]) {
    if (args.length < 2) {
      System.err.println("Usage: \"pgm exercise string-to-parse\"");
      System.err.println("Where \"exercise\" is one of: a b c d e f");
      return;
    }

    char exercise = args[0].charAt(0);
    if (!"abcdef".contains(String.valueOf(exercise))) {
      System.out.println("The given exercise does not exist");
      return;
    } else if ("cd".contains(String.valueOf(exercise))) {
      System.out.println("The given exercise does not yield a predictive " +
          "parsing table\n\t(On some nonterminal/input combination the " +
          "parsing table contains multiple productions to choose from.)");
      return;
    }

    ParseTables tables = new ParseTables();
    System.out.println(tables.getDescription(exercise));
    System.out.println("Word/String is " + (
        new Parser(
            tables.getParseTable(exercise),
            tables.getStartNonterminal(exercise),
            args[1]
        ).parse() ? "" : "**not** ") + "part of the language generated by the" +
        " grammar");
  }
}